name: Go Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  id-token: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@4b4e9c3e2d4531116a6f8ba8e71fc6e2cb6e6c8c # v2
      - uses: sigstore/cosign-installer@v3.0.3
      - uses: anchore/sbom-action/download-syft@v0.14.2
      - name: ghcr-login
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/login-action@465a07811f14bebb1938fbed4728c6a1ff8901fc # v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Go
        uses: actions/setup-go@v4
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.2.0'
      - name: Install signing key
        run: |
          echo '${{ secrets.COSIGN_PRIVATE_KEY }}' > cosign.key
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v4
        with:
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          COSIGN_PWD: ${{ secrets.COSIGN_PWD }}

      - name: Clean up & Logout from Container registries
        if: ${{ always() }}
        run: |
          docker logout
          docker logout ghcr.io
          rm -f cosign.key
  #sbom:
  #  name: sbom
  #  needs: [release]
  #  if: startsWith(github.ref, 'refs/tags/')
  #  runs-on: ubuntu-20.04
  #  env:
  #    TAGS: "${{ needs.release.outputs.container_tags }}"
#
  #  strategy:
  #    matrix:
  #      repo: ${{ fromJSON(needs.release.outputs.container_repos) }}
#
  #  steps:
  #    - name: Install cosign
  #      uses: sigstore/cosign-installer@11086d25041f77fe8fe7b9ea4e48e3b9192b8f19 # ratchet:sigstore/cosign-installer@v3.1.2
  #      with:
  #        cosign-release: 'v2.2.0'
#
  #    - name: Install Syft
  #      uses: anchore/sbom-action/download-syft@78fc58e266e87a38d4194b2137a3d4e9bcaf7ca1 # ratchet:anchore/sbom-action/download-syft@v0.14.3
  #    - name: Login to Container registries
  #      run: |
  #        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u philipssoftware --password-stdin
  #        echo "${{ secrets.GITHUB_TOKEN }}" | docker login -u ${{ github.actor }} --password-stdin ghcr.io
#
  #    - name: Attach SBOM
  #      env:
  #        COSIGN_PASSWORD: ${{ secrets.COSIGN_PASSWORD }}
  #      run: |
  #        echo '${{ secrets.COSIGN_PUBLIC_KEY }}' > cosign.pub
  #        echo '${{ secrets.COSIGN_PRIVATE_KEY }}' > cosign.key
  #        IFS=,
  #        for t in ${TAGS}; do
  #          cosign verify --key cosign.pub ${{ matrix.repo }}:${t}
  #          syft ${{ matrix.repo }}:${t} -o spdx-json > sbom-spdx.json
  #          cosign attest --predicate sbom-spdx.json --type spdx --key cosign.key ${{ matrix.repo }}:${t}
  #          cosign verify-attestation -o verified-sbom-spdx.json --key cosign.pub ${{ matrix.repo }}:${t}
  #        done
#
  #    - name: Clean up & Logout from Container registries
  #      if: ${{ always() }}
  #      run: |
  #        docker logout
  #        docker logout ghcr.io
  #        rm -f cosign.key
#
#
#