name: Release helm chart

on:
  push:
    tags:
      - "v*"

permissions: read-all

jobs:
  release-chart:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: "Extract Version"
        id: extract_version
        run: |
          GIT_TAG=${GITHUB_REF##*/}
          VERSION=${GIT_TAG##v}
          echo "::set-output name=version::$(echo $VERSION)"
      - name: Install Cosign
        uses: sigstore/cosign-installer@main
        with:
          cosign-release: 'v2.2.0'
      - name: Publish Helm chart
        uses: oliverbaehler/helm-oci-chart-releaser@main
        with:
          name: "cloudflare-tunnel-ingress-controller-chart"
          token: ${{ secrets.HELM_TOKEN }}
          path: "./helm/cloudflare-tunnel-ingress-controller/"
          app_version: ${{ steps.extract_version.outputs.version }}
          tag: ${{ steps.extract_version.outputs.version }}
          cosign_enabled: "true"
